spring:
  application:
    name: gateway

  cloud:
    eureka:
      client:
        enabled: ${EUREKA_ENABLED:false}
    kubernetes:
      discovery:
        enabled: ${K8S_DISCOVERY_ENABLED:false}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    root: ${LOG_LEVEL:INFO}