spring:
  application:
    name: gateway

  cloud:
    kubernetes:
      discovery:
        enabled: ${K8S_DISCOVERY_ENABLED:false}
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${FRONT_URL:https://yes-nhn.site}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    root: ${LOG_LEVEL:INFO}