apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  EUREKA_ENABLED: "false"
  K8S_DISCOVERY_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
